# Generated by Django 2.2 on 2020-04-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200417_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'vacancies'},
        ),
    ]
